### ISSUE TITLE
esp8266 error

### ISSUE THREAD

**Issue by tablatronix** [dplasa/dht#2]
```
error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in initialization
```

FIX:
esp8266 uint32
` volatile uint32_t *PIR = portInputRegister(port);`

**Comment by dplasa** [comment]
should be fixed upstream by letting the compiler deduct the type by using 
auto PIR = portInputRegister(port);

**Comment by tablatronix** [comment]
or wrap in esp condition, if you had to support older c++ maybe.
